import type { Perfume, ScentFamily } from '@/types';

export const scentFamilies: ScentFamily[] = ["Floral", "Woody", "Oriental", "Fresh", "Citrus"];

export const perfumes: Perfume[] = [
  {
    id: 1,
    name: 'Midnight Aura',
    scentFamily: 'Floral',
    topNotes: ['Jasmine', 'Tuberose'],
    heartNotes: ['Ylang-Ylang', 'Orange Blossom'],
    baseNotes: ['Sandalwood', 'Musk'],
    description: 'An intoxicating bouquet of night-blooming flowers, wrapped in a warm, woody embrace. Mysterious and unforgettable.',
    imageUrl: '/images/Midnight Aura.jpeg',
    isNew: true,
  },
  {
    id: 2,
    name: 'Woody Aura',
    scentFamily: 'Woody',
    topNotes: ['Pink Pepper', 'Bergamot'],
    heartNotes: ['Cedarwood', 'Vetiver'],
    baseNotes: ['Amber', 'Oud'],
    description: 'A rich, smoky scent that evokes a crackling fireplace in a secluded forest cabin. For the bold and contemplative.',
    imageUrl: '/images/Woody Aura.jpeg',
    isNew: true,
  },
  {
    id: 3,
    name: 'Citrus Aura',
    scentFamily: 'Citrus',
    topNotes: ['Lemon', 'Mandarin Orange'],
    heartNotes: ['Basil', 'Neroli'],
    baseNotes: ['Musk', 'Green Tea'],
    description: 'A vibrant and zesty fragrance, bursting with sun-ripened citrus fruits and fresh herbs. Energetic and uplifting.',
    imageUrl: '/images/Citrus Aura.jpeg',
    isNew: false,
  },
  {
    id: 4,
    name: 'Aura Bloom',
    scentFamily: 'Floral',
    topNotes: ['Peony', 'Lychee'],
    heartNotes: ['Rose', 'Magnolia'],
    baseNotes: ['Cedar', 'Ambergris'],
    description: 'A soft, romantic floral that feels like being enveloped in a cloud of pink petals. Delicate and gracefully feminine.',
    imageUrl: '/images/Aura Bloom.jpeg',
    isNew: false,
  },
  {
    id: 5,
    name: 'Golden Hour',
    scentFamily: 'Oriental',
    topNotes: ['Saffron', 'Cinnamon'],
    heartNotes: ['Turkish Rose', 'Vanilla'],
    baseNotes: ['Patchouli', 'Frankincense'],
    description: 'A warm, spicy, and opulent fragrance that captures the magic of a sunset. Luxurious and deeply sensual.',
    imageUrl: '/images/Golden Hour.jpeg',
    isNew: false,
  },
  {
    id: 6,
    name: 'Coastal Drift',
    scentFamily: 'Fresh',
    topNotes: ['Sea Salt', 'Grapefruit'],
    heartNotes: ['Sage', 'Seaweed'],
    baseNotes: ['Driftwood', 'Ambrette'],
    description: 'A clean, invigorating scent that brings to mind a brisk walk along a windswept coast. Crisp, and liberating.',
    imageUrl: '/images/Coastal Drift.jpeg',
    isNew: false,
  },
   {
    id: 7,
    name: 'Crimson Spice',
    scentFamily: 'Oriental',
    topNotes: ['Cardamom', 'Clove'],
    heartNotes: ['Plum', 'Tobacco'],
    baseNotes: ['Tonka Bean', 'Benzoin'],
    description: 'A daring and provocative blend of rich spices and dark fruit. Perfect for making a memorable statement.',
    imageUrl: '/images/Crimson Spice.jpeg',
    isNew: true,
  },
  {
    id: 8,
    name: 'Forest Floor',
    scentFamily: 'Woody',
    topNotes: ['Pine Needle', 'Cypress'],
    heartNotes: ['Oakmoss', 'Mushroom'],
    baseNotes: ['Patchouli', 'Black Truffle'],
    description: 'An earthy, grounding fragrance that smells of damp earth and ancient trees after a rainfall. Deeply calming.',
    imageUrl: '/images/Forest Floor.jpeg',
    isNew: false,
  },
];
